package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvoiceLine implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Product")
    private String product;
    @org.kie.api.definition.type.Label("Quantity")
    private Integer quantity;
    @org.kie.api.definition.type.Label("Price")
    private Double price;
    @org.kie.api.definition.type.Label("Total")
    private Double total;

    public InvoiceLine() {
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public InvoiceLine(String product,
                       Integer quantity,
                       Double price,
                       Double total) {
        this.product = product;
        this.quantity = quantity;
        this.price = price;
        this.total = total;
    }
}
